In [218]:
import pandas as pd

In [219]:
pd.__version__

'3.0.1'

In [220]:
my_series = pd.Series([10,20,30,40,50], index = ["a","b","c","d","e"])
my_series

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [221]:
type(my_series)

pandas.Series

In [222]:
my_series["a"]

np.int64(10)

In [223]:
my_series["b":"d"]

b    20
c    30
d    40
dtype: int64

In [224]:
my_series

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [225]:
my_series + 5

a    15
b    25
c    35
d    45
e    55
dtype: int64

In [226]:
my_series * 2

a     20
b     40
c     60
d     80
e    100
dtype: int64

In [227]:
# type(my_series[0])

In [228]:
my_series.dtype

dtype('int64')

In [229]:
my_series.size

5

In [230]:
my_series.shape

(5,)

In [231]:
my_series.head(3)

a    10
b    20
c    30
dtype: int64

In [232]:
my_series.tail(2)

d    40
e    50
dtype: int64

In [233]:
my_series.describe()

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [234]:
my_series.sort_values(ascending = False)

e    50
d    40
c    30
b    20
a    10
dtype: int64

In [235]:
data = { "Name": ["John", "Emily", "Kate", "Sam"],
        "Age": [25,30,28,35],
        "City": ["New York", "San Francisco", "Chicago", "Seattle"]}

In [236]:
data

{'Name': ['John', 'Emily', 'Kate', 'Sam'],
 'Age': [25, 30, 28, 35],
 'City': ['New York', 'San Francisco', 'Chicago', 'Seattle']}

In [237]:
df = pd.DataFrame(data)

In [238]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [239]:
data_list = [["John",25,"New York"], ["Emily",30,"San Francisco"], ["Kate",28,"Chicago"], ["Sam",35,"Seattle"]]

In [240]:
data_list

[['John', 25, 'New York'],
 ['Emily', 30, 'San Francisco'],
 ['Kate', 28, 'Chicago'],
 ['Sam', 35, 'Seattle']]

In [241]:
df_list = pd.DataFrame(data_list, columns = ["Name", "Age", "City"])

In [242]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [243]:
df_list

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [244]:
import numpy as np

In [245]:
data_array = np.array ( [[1,2,3],[4,5,6],[7,8,9]])

In [246]:
data_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [247]:
df_array = pd.DataFrame(data_array, columns = ["A","B","C"])

In [248]:
df_array

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [249]:
data = { "Name": ["John", "Emily", "Kate", "Sam"],
        "Age": [25,30,28,35],
        "City": ["New York", "San Francisco", "Chicago", "Seattle"]}
df = pd.DataFrame(data)
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [250]:
df.to_csv("example.csv", index = False)

In [251]:
data = pd.read_csv("example.csv")

In [252]:
data

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [253]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [254]:
#df.to_excel("example.xlsx", index = False)

In [255]:
#data_excel = pd.read_excel("example.xlsx")

In [256]:
#data_excel

In [257]:
data = { "Name": ["John", "Emily", "Kate", "Sam"],
        "Age": [25,30,28,35],
        "City": ["New York", "San Francisco", "Chicago", "Seattle"]}
df = pd.DataFrame(data)
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [258]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [259]:
df.head(2) #df.tail()

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco

In [260]:
df[["Name","City"]]

    Name           City
0   John       New York
1  Emily  San Francisco
2   Kate        Chicago
3    Sam        Seattle

In [261]:
df #df["Name"] #df[["Name"]].values

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [262]:
df[df["Age"] >= 28]

    Name  Age           City
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [263]:
df[df["Name"] == "John"]

   Name  Age      City
0  John   25  New York

In [264]:
df[(df["City"] == "New York") & (df["Age"] < 20)]

Empty DataFrame
Columns: [Name, Age, City]
Index: []

In [265]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [266]:
selected_cities = ["New York", "Seattle"]

In [267]:
df[df["City"].isin(selected_cities)]

   Name  Age      City
0  John   25  New York
3   Sam   35   Seattle

In [268]:
df[df["Name"].str.startswith("J")]

   Name  Age      City
0  John   25  New York

In [269]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [270]:
df.iloc[0 : 2]

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco

In [271]:
df.loc[df["Age"] > 28,["Name","City"]]

    Name           City
1  Emily  San Francisco
3    Sam        Seattle

In [272]:
import numpy as np

In [273]:
np.nan

nan

In [274]:
data = {'A': [1, 2, np.nan, 4, 5],
        'B': [6, np.nan, 8, 9, 10],
        'C': [11, 12, 13, np.nan, 15]}
df = pd.DataFrame(data)
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   8.0  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [275]:
df.isnull()

       A      B      C
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False   True
4  False  False  False

In [276]:
df.isnull().sum()

A    1
B    1
C    1
dtype: int64

In [277]:
df.dropna()

     A     B     C
0  1.0   6.0  11.0
4  5.0  10.0  15.0

In [278]:
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   8.0  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [279]:
df.dropna(inplace = True) #df = df.dropna()

In [280]:
df

     A     B     C
0  1.0   6.0  11.0
4  5.0  10.0  15.0

In [281]:
data = {'A': [1, 2, np.nan, 4, 5],
        'B': [6, np.nan, np.nan, 9, 10],
        'C': [11, 12, 13, np.nan, 15]}
df = pd.DataFrame(data)
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   NaN  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [282]:
df.dropna(axis = 0)

     A     B     C
0  1.0   6.0  11.0
4  5.0  10.0  15.0

In [283]:
df.dropna(thresh=1)

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   NaN  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [284]:
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   NaN  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [285]:
df.fillna(0)

     A     B     C
0  1.0   6.0  11.0
1  2.0   0.0  12.0
2  0.0   0.0  13.0
3  4.0   9.0   0.0
4  5.0  10.0  15.0

In [286]:
df.fillna(df.mean())

     A          B      C
0  1.0   6.000000  11.00
1  2.0   8.333333  12.00
2  3.0   8.333333  13.00
3  4.0   9.000000  12.75
4  5.0  10.000000  15.00

In [287]:
df.fillna(df.median()) #mean, min, max

     A     B     C
0  1.0   6.0  11.0
1  2.0   9.0  12.0
2  3.0   9.0  13.0
3  4.0   9.0  12.5
4  5.0  10.0  15.0

In [288]:
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   NaN  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [311]:
# df.fillna(method = "ffill")

In [297]:
data = {'A': [1, 2, 3, 4, 5],
        'B': [6, 7, 8, 9, 10],
        'C': [11, 12, 13, 14, 15]}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
df

   A   B   C
a  1   6  11
b  2   7  12
c  3   8  13
d  4   9  14
e  5  10  15

In [304]:
df.loc[["a","e"],["A","C"]]

   A   C
a  1  11
e  5  15

In [305]:
df

   A   B   C
a  1   6  11
b  2   7  12
c  3   8  13
d  4   9  14
e  5  10  15

In [310]:
df.iloc[[0,2]]

   A  B   C
a  1  6  11
c  3  8  13

In [312]:
data = { "Name": ["John", "Emily", "Kate", "Sam"],
        "Age": [25,30,28,35],
        "City": ["New York", "San Francisco", "Chicago", "Seattle"]}
df = pd.DataFrame(data)

In [313]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [314]:
df[df["Age"] < 32]

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago

In [316]:
df[(df["City"] == "Chicago") & (df["Age"] < 30)]

   Name  Age     City
2  Kate   28  Chicago

In [317]:
df.query("Age > 28")

    Name  Age           City
1  Emily   30  San Francisco
3    Sam   35        Seattle

In [ ]:
df.query("Age > 28 and City == 'San Francisco'") #or to satisfy some not all conditions

    Name  Age           City
1  Emily   30  San Francisco

In [319]:
df.query("Age * 2 > 50")

    Name  Age           City
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [320]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [321]:
df.sort_values("Age", ascending= False)

    Name  Age           City
3    Sam   35        Seattle
1  Emily   30  San Francisco
2   Kate   28        Chicago
0   John   25       New York

In [322]:
df.sort_values(["City","Age"])

    Name  Age           City
2   Kate   28        Chicago
0   John   25       New York
1  Emily   30  San Francisco
3    Sam   35        Seattle

In [326]:
df["Age"].rank(method = "min")

0    1.0
1    3.0
2    2.0
3    4.0
Name: Age, dtype: float64

In [328]:
data1 = {'A': [1, 2, 3],
         'B': [4, 5, 6]}
data2 = {'A': [7, 8, 9],
         'B': [10, 11, 12]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [329]:
df1

   A  B
0  1  4
1  2  5
2  3  6

In [330]:
df2

   A   B
0  7  10
1  8  11
2  9  12

In [331]:
pd.concat([df1,df2])

   A   B
0  1   4
1  2   5
2  3   6
0  7  10
1  8  11
2  9  12

In [332]:
pd.concat([df1,df2], axis = 1)

   A  B  A   B
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

In [333]:
data3 = {'A': [1, 2, 3],
         'C': [13, 14, 15]}
df3 = pd.DataFrame(data3)

In [ ]:
df1

   A  B
0  1  4
1  2  5
2  3  6

In [335]:
df3

   A   C
0  1  13
1  2  14
2  3  15

In [336]:
pd.merge(df1,df3, on= "A")

   A  B   C
0  1  4  13
1  2  5  14
2  3  6  15

In [348]:
# Data Cleaning
data = {'A': [1, 2, 2, 3, 11, 11],
        'B': [1, 5, 5, 6, 12, 25]}
df = pd.DataFrame(data)

In [349]:
df

    A   B
0   1   1
1   2   5
2   2   5
3   3   6
4  11  12
5  11  25

In [350]:
df.duplicated().sum()

np.int64(1)

In [351]:
df.drop_duplicates()

    A   B
0   1   1
1   2   5
3   3   6
4  11  12
5  11  25

In [352]:
df.drop_duplicates(subset = ["A"])

    A   B
0   1   1
1   2   5
3   3   6
4  11  12

In [353]:
df.describe()

               A          B
count   6.000000   6.000000
mean    5.000000   9.000000
std     4.690416   8.602325
min     1.000000   1.000000
25%     2.000000   5.000000
50%     2.500000   5.500000
75%     9.000000  10.500000
max    11.000000  25.000000

In [354]:
q_low = df["B"].quantile(0.25)

In [355]:
q_high = df["B"].quantile(0.75)

In [357]:
q_range = q_high - q_low

In [360]:
df

    A   B
0   1   1
1   2   5
2   2   5
3   3   6
4  11  12
5  11  25

In [ ]:
lower_bound = q_low - 1.15 * q_range
upper_bound = q_high + 1.5 * q_range

In [364]:
df_filtered = df[(df["B"] > lower_bound) & (df["B"] < upper_bound)]
df_filtered

    A   B
0   1   1
1   2   5
2   2   5
3   3   6
4  11  12

In [383]:
data = {'Category': ['A', 'B', 'A', 'C', 'B', 'A']}
        #"Sales" : [10,20,30,40,50,60]}
df = pd.DataFrame(data)

In [384]:
df

  Category
0        A
1        B
2        A
3        C
4        B
5        A

In [385]:
pd.get_dummies(df["Category"])

       A      B      C
0   True  False  False
1  False   True  False
2   True  False  False
3  False  False   True
4  False   True  False
5   True  False  False

In [370]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df["Category_Labelencoder"] = label_encoder.fit_transform(df["Category"])

In [386]:
df

  Category
0        A
1        B
2        A
3        C
4        B
5        A

In [390]:
df.groupby("Category").size().reset_index()

  Category  0
0        A  3
1        B  2
2        C  1

In [391]:
df.groupby("Category").agg({"Category":"count"})

          Category
Category
A                3
B                2
C                1