In [414]:
import pandas as pd

In [415]:
pd.__version__

'3.0.1'

In [416]:
my_series = pd.Series([10,20,30,40,50], index = ["a","b","c","d","e"])
my_series

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [417]:
type(my_series)

pandas.Series

In [418]:
my_series["a"]

np.int64(10)

In [419]:
my_series["b":"d"]

b    20
c    30
d    40
dtype: int64

In [420]:
my_series

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [421]:
my_series + 5

a    15
b    25
c    35
d    45
e    55
dtype: int64

In [422]:
my_series * 2

a     20
b     40
c     60
d     80
e    100
dtype: int64

In [423]:
# type(my_series[0])

In [424]:
my_series.dtype

dtype('int64')

In [425]:
my_series.size

5

In [426]:
my_series.shape

(5,)

In [427]:
my_series.head(3)

a    10
b    20
c    30
dtype: int64

In [428]:
my_series.tail(2)

d    40
e    50
dtype: int64

In [429]:
my_series.describe()

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [430]:
my_series.sort_values(ascending = False)

e    50
d    40
c    30
b    20
a    10
dtype: int64

In [431]:
data = { "Name": ["John", "Emily", "Kate", "Sam"],
        "Age": [25,30,28,35],
        "City": ["New York", "San Francisco", "Chicago", "Seattle"]}

In [432]:
data

{'Name': ['John', 'Emily', 'Kate', 'Sam'],
 'Age': [25, 30, 28, 35],
 'City': ['New York', 'San Francisco', 'Chicago', 'Seattle']}

In [433]:
df = pd.DataFrame(data)

In [434]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [435]:
data_list = [["John",25,"New York"], ["Emily",30,"San Francisco"], ["Kate",28,"Chicago"], ["Sam",35,"Seattle"]]

In [436]:
data_list

[['John', 25, 'New York'],
 ['Emily', 30, 'San Francisco'],
 ['Kate', 28, 'Chicago'],
 ['Sam', 35, 'Seattle']]

In [437]:
df_list = pd.DataFrame(data_list, columns = ["Name", "Age", "City"])

In [438]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [439]:
df_list

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [440]:
import numpy as np

In [441]:
data_array = np.array ( [[1,2,3],[4,5,6],[7,8,9]])

In [442]:
data_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [443]:
df_array = pd.DataFrame(data_array, columns = ["A","B","C"])

In [444]:
df_array

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [445]:
data = { "Name": ["John", "Emily", "Kate", "Sam"],
        "Age": [25,30,28,35],
        "City": ["New York", "San Francisco", "Chicago", "Seattle"]}
df = pd.DataFrame(data)
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [446]:
df.to_csv("example.csv", index = False)

In [447]:
data = pd.read_csv("example.csv")

In [448]:
data

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [449]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [450]:
#df.to_excel("example.xlsx", index = False)

In [451]:
#data_excel = pd.read_excel("example.xlsx")

In [452]:
#data_excel

In [453]:
data = { "Name": ["John", "Emily", "Kate", "Sam"],
        "Age": [25,30,28,35],
        "City": ["New York", "San Francisco", "Chicago", "Seattle"]}
df = pd.DataFrame(data)
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [454]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [455]:
df.head(2) #df.tail()

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco

In [456]:
df[["Name","City"]]

    Name           City
0   John       New York
1  Emily  San Francisco
2   Kate        Chicago
3    Sam        Seattle

In [457]:
df #df["Name"] #df[["Name"]].values

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [458]:
df[df["Age"] >= 28]

    Name  Age           City
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [459]:
df[df["Name"] == "John"]

   Name  Age      City
0  John   25  New York

In [460]:
df[(df["City"] == "New York") & (df["Age"] < 20)]

Empty DataFrame
Columns: [Name, Age, City]
Index: []

In [461]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [462]:
selected_cities = ["New York", "Seattle"]

In [463]:
df[df["City"].isin(selected_cities)]

   Name  Age      City
0  John   25  New York
3   Sam   35   Seattle

In [464]:
df[df["Name"].str.startswith("J")]

   Name  Age      City
0  John   25  New York

In [465]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [466]:
df.iloc[0 : 2]

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco

In [467]:
df.loc[df["Age"] > 28,["Name","City"]]

    Name           City
1  Emily  San Francisco
3    Sam        Seattle

In [468]:
import numpy as np

In [469]:
np.nan

nan

In [470]:
data = {'A': [1, 2, np.nan, 4, 5],
        'B': [6, np.nan, 8, 9, 10],
        'C': [11, 12, 13, np.nan, 15]}
df = pd.DataFrame(data)
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   8.0  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [471]:
df.isnull()

       A      B      C
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False   True
4  False  False  False

In [472]:
df.isnull().sum()

A    1
B    1
C    1
dtype: int64

In [473]:
df.dropna()

     A     B     C
0  1.0   6.0  11.0
4  5.0  10.0  15.0

In [474]:
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   8.0  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [475]:
df.dropna(inplace = True) #df = df.dropna()

In [476]:
df

     A     B     C
0  1.0   6.0  11.0
4  5.0  10.0  15.0

In [477]:
data = {'A': [1, 2, np.nan, 4, 5],
        'B': [6, np.nan, np.nan, 9, 10],
        'C': [11, 12, 13, np.nan, 15]}
df = pd.DataFrame(data)
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   NaN  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [478]:
df.dropna(axis = 0)

     A     B     C
0  1.0   6.0  11.0
4  5.0  10.0  15.0

In [479]:
df.dropna(thresh=1)

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   NaN  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [480]:
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   NaN  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [481]:
df.fillna(0)

     A     B     C
0  1.0   6.0  11.0
1  2.0   0.0  12.0
2  0.0   0.0  13.0
3  4.0   9.0   0.0
4  5.0  10.0  15.0

In [482]:
df.fillna(df.mean())

     A          B      C
0  1.0   6.000000  11.00
1  2.0   8.333333  12.00
2  3.0   8.333333  13.00
3  4.0   9.000000  12.75
4  5.0  10.000000  15.00

In [483]:
df.fillna(df.median()) #mean, min, max

     A     B     C
0  1.0   6.0  11.0
1  2.0   9.0  12.0
2  3.0   9.0  13.0
3  4.0   9.0  12.5
4  5.0  10.0  15.0

In [484]:
df

     A     B     C
0  1.0   6.0  11.0
1  2.0   NaN  12.0
2  NaN   NaN  13.0
3  4.0   9.0   NaN
4  5.0  10.0  15.0

In [485]:
# df.fillna(method = "ffill")

In [486]:
data = {'A': [1, 2, 3, 4, 5],
        'B': [6, 7, 8, 9, 10],
        'C': [11, 12, 13, 14, 15]}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])
df

   A   B   C
a  1   6  11
b  2   7  12
c  3   8  13
d  4   9  14
e  5  10  15

In [487]:
df.loc[["a","e"],["A","C"]]

   A   C
a  1  11
e  5  15

In [488]:
df

   A   B   C
a  1   6  11
b  2   7  12
c  3   8  13
d  4   9  14
e  5  10  15

In [489]:
df.iloc[[0,2]]

   A  B   C
a  1  6  11
c  3  8  13

In [490]:
data = { "Name": ["John", "Emily", "Kate", "Sam"],
        "Age": [25,30,28,35],
        "City": ["New York", "San Francisco", "Chicago", "Seattle"]}
df = pd.DataFrame(data)

In [491]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [492]:
df[df["Age"] < 32]

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago

In [493]:
df[(df["City"] == "Chicago") & (df["Age"] < 30)]

   Name  Age     City
2  Kate   28  Chicago

In [494]:
df.query("Age > 28")

    Name  Age           City
1  Emily   30  San Francisco
3    Sam   35        Seattle

In [495]:
df.query("Age > 28 and City == 'San Francisco'") #or to satisfy some not all conditions

    Name  Age           City
1  Emily   30  San Francisco

In [496]:
df.query("Age * 2 > 50")

    Name  Age           City
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [497]:
df

    Name  Age           City
0   John   25       New York
1  Emily   30  San Francisco
2   Kate   28        Chicago
3    Sam   35        Seattle

In [498]:
df.sort_values("Age", ascending= False)

    Name  Age           City
3    Sam   35        Seattle
1  Emily   30  San Francisco
2   Kate   28        Chicago
0   John   25       New York

In [499]:
df.sort_values(["City","Age"])

    Name  Age           City
2   Kate   28        Chicago
0   John   25       New York
1  Emily   30  San Francisco
3    Sam   35        Seattle

In [500]:
df["Age"].rank(method = "min")

0    1.0
1    3.0
2    2.0
3    4.0
Name: Age, dtype: float64

In [501]:
data1 = {'A': [1, 2, 3],
         'B': [4, 5, 6]}
data2 = {'A': [7, 8, 9],
         'B': [10, 11, 12]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

In [502]:
df1

   A  B
0  1  4
1  2  5
2  3  6

In [503]:
df2

   A   B
0  7  10
1  8  11
2  9  12

In [504]:
pd.concat([df1,df2])

   A   B
0  1   4
1  2   5
2  3   6
0  7  10
1  8  11
2  9  12

In [505]:
pd.concat([df1,df2], axis = 1)

   A  B  A   B
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

In [506]:
data3 = {'A': [1, 2, 3],
         'C': [13, 14, 15]}
df3 = pd.DataFrame(data3)

In [507]:
df1

   A  B
0  1  4
1  2  5
2  3  6

In [508]:
df3

   A   C
0  1  13
1  2  14
2  3  15

In [509]:
pd.merge(df1,df3, on= "A")

   A  B   C
0  1  4  13
1  2  5  14
2  3  6  15

In [510]:
# Data Cleaning
data = {'A': [1, 2, 2, 3, 11, 11],
        'B': [1, 5, 5, 6, 12, 25]}
df = pd.DataFrame(data)

In [511]:
df

    A   B
0   1   1
1   2   5
2   2   5
3   3   6
4  11  12
5  11  25

In [512]:
df.duplicated().sum()

np.int64(1)

In [513]:
df.drop_duplicates()

    A   B
0   1   1
1   2   5
3   3   6
4  11  12
5  11  25

In [514]:
df.drop_duplicates(subset = ["A"])

    A   B
0   1   1
1   2   5
3   3   6
4  11  12

In [515]:
df.describe()

               A          B
count   6.000000   6.000000
mean    5.000000   9.000000
std     4.690416   8.602325
min     1.000000   1.000000
25%     2.000000   5.000000
50%     2.500000   5.500000
75%     9.000000  10.500000
max    11.000000  25.000000

In [516]:
q_low = df["B"].quantile(0.25)

In [517]:
q_high = df["B"].quantile(0.75)

In [518]:
q_range = q_high - q_low

In [519]:
df

    A   B
0   1   1
1   2   5
2   2   5
3   3   6
4  11  12
5  11  25

In [520]:
lower_bound = q_low - 1.15 * q_range
upper_bound = q_high + 1.5 * q_range

In [521]:
df_filtered = df[(df["B"] > lower_bound) & (df["B"] < upper_bound)]
df_filtered

    A   B
0   1   1
1   2   5
2   2   5
3   3   6
4  11  12

In [522]:
data = {'Category': ['A', 'B', 'A', 'C', 'B', 'A']}
        #"Sales" : [10,20,30,40,50,60]}
df = pd.DataFrame(data)

In [523]:
df

  Category
0        A
1        B
2        A
3        C
4        B
5        A

In [524]:
pd.get_dummies(df["Category"])

       A      B      C
0   True  False  False
1  False   True  False
2   True  False  False
3  False  False   True
4  False   True  False
5   True  False  False

In [525]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df["Category_Labelencoder"] = label_encoder.fit_transform(df["Category"])

In [526]:
df

  Category  Category_Labelencoder
0        A                      0
1        B                      1
2        A                      0
3        C                      2
4        B                      1
5        A                      0

In [527]:
df.groupby("Category").size().reset_index()

  Category  0
0        A  3
1        B  2
2        C  1

In [528]:
df.groupby("Category").agg({"Category":"count"})

          Category
Category
A                3
B                2
C                1

In [529]:
data = {'Name': ['John', 'Emily', 'Kate'],
        'Math': [90, 85, 88],
        'Science': [92, 80, 95]}
df = pd.DataFrame(data)

In [530]:
df

    Name  Math  Science
0   John    90       92
1  Emily    85       80
2   Kate    88       95

In [531]:
df_melted = pd.melt(df, id_vars= ["Name"], var_name = "Subject", value_name = "Score")

In [532]:
df_melted

    Name  Subject  Score
0   John     Math     90
1  Emily     Math     85
2   Kate     Math     88
3   John  Science     92
4  Emily  Science     80
5   Kate  Science     95

In [533]:
df_melted .pivot(index = "Name",columns = "Subject", values = "Score")

Subject  Math  Science
Name
Emily      85       80
John       90       92
Kate       88       95

In [534]:
# Working with time series data
data = {'Date': ['2023-01-01', '2023-01-02', '2023-01-03'],
        'Sales': [100, 150, 200]}
df = pd.DataFrame(data)

In [535]:
df

         Date  Sales
0  2023-01-01    100
1  2023-01-02    150
2  2023-01-03    200

In [536]:
df["Date"] = pd.to_datetime(df["Date"])
df.dtypes

Date     datetime64[us]
Sales             int64
dtype: object

In [537]:
df

        Date  Sales
0 2023-01-01    100
1 2023-01-02    150
2 2023-01-03    200

In [538]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

In [539]:
df

        Date  Sales  Year  Month  Day
0 2023-01-01    100  2023      1    1
1 2023-01-02    150  2023      1    2
2 2023-01-03    200  2023      1    3

In [540]:
time_index = pd.date_range('2023-01-01', periods=5, freq = 'D')
ts_data = pd.Series([100, 120, 80, 110, 90], index=time_index)

In [541]:
ts_data

2023-01-01    100
2023-01-02    120
2023-01-03     80
2023-01-04    110
2023-01-05     90
Freq: D, dtype: int64

In [543]:
ts_resampled = ts_data.resample("YE").mean()
ts_resampled

2023-12-31    100.0
Freq: YE-DEC, dtype: float64

In [545]:
data = {'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05'],
        'Sales': [100, 150, 200,120,180]}
df = pd.DataFrame(data)
df

         Date  Sales
0  2023-01-01    100
1  2023-01-02    150
2  2023-01-03    200
3  2023-01-04    120
4  2023-01-05    180

In [547]:
df["Date"] = pd.to_datetime(df["Date"])

In [549]:
df.set_index("Date", inplace = True)

In [550]:
df

            Sales
Date
2023-01-01    100
2023-01-02    150
2023-01-03    200
2023-01-04    120
2023-01-05    180

In [552]:
df["Shifted_Sales"] = df["Sales"].shift(1)
df["Shifted_Sales"] = df["Sales"].shift(-1)

In [555]:
df

            Sales  Shifted_Sales
Date
2023-01-01    100          150.0
2023-01-02    150          200.0
2023-01-03    200          120.0
2023-01-04    120          180.0
2023-01-05    180            NaN

In [ ]:
date_range = pd.date_range(start="2023-01-01", periods=20, freq="ME") #valuable for forecasting

In [564]:
date_range

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30', '2023-10-31', '2023-11-30', '2023-12-31',
               '2024-01-31', '2024-02-29', '2024-03-31', '2024-04-30',
               '2024-05-31', '2024-06-30', '2024-07-31', '2024-08-31'],
              dtype='datetime64[us]', freq='ME')

In [567]:
data = {'Category': ['A', 'B', 'A', 'B', 'A'],
        'Value': [10, 15, 20, 25, 30]}
df = pd.DataFrame(data)
df

  Category  Value
0        A     10
1        B     15
2        A     20
3        B     25
4        A     30

In [ ]:
df.groupby("Category").sum() #.mean #.median #.max #.min #.var #.std

          Value
Category
A            60
B            40

In [569]:
df.groupby("Category").agg(["sum", "mean", "max"])

         Value
           sum  mean max
Category
A           60  20.0  30
B           40  20.0  25